server:
  port: 9002

spring:
  application:
    name: CANDIDATE-SERVICE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://3.128.91.25:31200/Checkr
    username: root
    password: Bootcamp@125


  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
      format-sql: true

  flyway:
    baseline-on-migrate: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: false
    hostname: localhost
