apiVersion: apps/v1
kind: Deployment
metadata:
   name: be-api-gateway-deployment
   labels:
      type: api-gateway-deployment
      app: backend-ag-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: api-gateway
  template:
    metadata:
      name: api-gateway-pod
      labels:
        type: api-gateway
    spec:
      containers:
      - name: bc125-backend-api-gateway
        image: ghcr.io/paritosh-pranjal/bc125-be-eks-api-gateway:v4
        ports:
        - containerPort: 9191
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: http://service-registry-svc:8761/eureka/
          - name: EUREKA_INSTANCE_HOSTNAME
            value: api-gateway-svc
          - name: SECRET_ID
            value: fafc32a5fbfbbc900cf423a70724c324302c1eccbf5f998ef4485895e43c44d5

      imagePullSecrets: 
      - name: ghcr-secret
