apiVersion: apps/v1
kind: Deployment
metadata:
   name: be-courtsearches-service-deployment
   labels:
      type: courtsearches-service-deployment
      app: backend-us-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: courtsearches-service
  template:
    metadata:
      name: courtsearches-service-pod
      labels:
        type: courtsearches-service
    spec:
      containers:
      - name: bc125-backend-courtsearches-service
        image: ghcr.io/paritosh-pranjal/bc125-be-eks-courtsearches-service:v4
        ports:
        - containerPort: 9003
        env:
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: http://service-registry-svc:8761/eureka/
          - name: EUREKA_INSTANCE_HOSTNAME
            value: courtsearches-service-svc
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://3.128.91.25:31592/Checkr
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: username
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: database-secret
                  key: password
          - name: SPRING_FLYWAY_URL
            value: jdbc:mysql://3.128.91.25:31592/Checkr 
          - name: SPRING_FLYWAY_USER
            valueFrom:
              secretKeyRef:
                name: database-secret
                key: username
          - name: SPRING_FLYWAY_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: database-secret
                  key: password
      imagePullSecrets: 
      - name: ghcr-secret
